language: csharp
solution: ComparePG.sln
deploy:
  provider: releases
  api_key: "f8ff459252a30b9eb7afb505b6c2e17cd37e77c7"
  file_glob: true
  file: 
    - "ComparePG/bin/Release/ComparePG.exe"
    - "ComparePG/bin/Release/Npgsql.dll"
    - "ComparePG/bin/Release/System.Threading.Tasks.Extensions.dll"
  skip_cleanup: true
  on:
    tags: true