language: csharp
solution: ComparePG.sln
deploy:
  provider: releases
  api_key: "21a5bf503d468471ed035640440e13c45bab4c9f"
  file_glob: true
  file: 
    - "ComparePG/bin/Release/ComparePG.exe"
    - "ComparePG/bin/Release/Npgsql.dll"
    - "ComparePG/bin/Release/System.Threading.Tasks.Extensions.dll"
  skip_cleanup: true
  on:
    tags: true